<template>
    <div class="container mx-auto px-4 py-8 sm:py-12 prose prose-invert max-w-3xl">
        <h1>Terms of Service for DeepSocial AI</h1>
        <p>Last updated: [Date]</p>

        <p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the DeepSocial AI
            website and any services offered by DeepSocial AI (the "Service") operated by [Your Company Name/Your Name]
            ("us", "we", or "our").</p>
        <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.
            These Terms apply to all visitors, users, and others who access or use the Service. By accessing or using
            the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may
            not access the Service.</p>

        <h2>1. Description of Service</h2>
        <p>DeepSocial AI provides an AI-powered service designed to analyze social media content, help identify
            misinformation, detect biases, and provide users with tools for fact-checking and understanding online
            narratives (the "Service"). The features and functionalities may evolve over time.</p>

        <h2>2. Waitlist</h2>
        <p>By joining our waitlist, you agree to receive email communications from us regarding updates about
            DeepSocial AI, including notifications about service availability, beta programs, and promotional
            materials. You can unsubscribe from these communications at any time by following the unsubscribe link in
            the emails.</p>

        <h2>3. User Accounts (If applicable in the future)</h2>
        <p>When you create an account with us (once the service is live), you must provide information that is accurate,
            complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in
            immediate termination of your account on our Service.</p>
        <p>You are responsible for safeguarding the password that you use to access the Service and for any activities
            or actions under your password, whether your password is with our Service or a third-party service.</p>

        <h2>4. Acceptable Use Policy</h2>
        <p>You agree not to use the Service:</p>
        <ul>
            <li>In any way that violates any applicable national or international law or regulation.</li>
            <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any "junk
                mail", "chain letter," "spam," or any other similar solicitation.</li>
            <li>To impersonate or attempt to impersonate DeepSocial AI, a DeepSocial AI employee, another user, or any
                other person or entity.</li>
            <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Service, or
                which, as determined by us, may harm DeepSocial AI or users of the Service or expose them to liability.
            </li>
            <li>To attempt to reverse engineer, decompile, or otherwise attempt to discover the source code or
                underlying ideas or algorithms of the Service.</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <p>The Service and its original content (excluding content provided by users, if applicable in the future),
            features, and functionality are and will remain the exclusive property of [Your Company Name/Your Name] and
            its licensors. Our trademarks and trade dress may not be used in connection with any product or service
            without the prior written consent of [Your Company Name/Your Name].</p>
        <p>The analyses, reports, and insights generated by DeepSocial AI for you are for your use as permitted by the
            Service. You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service,
            use of the Service, or access to the Service without express written permission by us.</p>

        <h2>6. AI Generated Content and Limitations</h2>
        <p>DeepSocial AI utilizes artificial intelligence, which may sometimes produce inaccurate, incomplete, or
            biased information. While we strive for accuracy and fairness, you acknowledge that:</p>
        <ul>
            <li>The information provided by the Service is for informational purposes only and should not be solely
                relied upon for making critical decisions.</li>
            <li>You are responsible for independently verifying any critical information.</li>
            <li>We are not liable for any errors, omissions, or inaccuracies in the AI-generated content or for any
                reliance placed on such information.</li>
        </ul>

        <h2>7. Termination</h2>
        <p>We may terminate or suspend your access to our Service immediately, without prior notice or liability, for
            any reason whatsoever, including without limitation if you breach the Terms.</p>
        <p>All provisions of the Terms which by their nature should survive termination shall survive termination,
            including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of
            liability.</p>

        <h2>8. Disclaimer of Warranties</h2>
        <p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis.
            The Service is provided without warranties of any kind, whether express or implied, including, but not
            limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or
            course of performance.</p>
        <p>[Your Company Name/Your Name] its subsidiaries, affiliates, and its licensors do not warrant that a) the
            Service will function uninterrupted, secure or available at any particular time or location; b) any errors
            or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the
            results of using the Service will meet your requirements.</p>

        <h2>9. Limitation of Liability</h2>
        <p>In no event shall [Your Company Name/Your Name], nor its directors, employees, partners, agents, suppliers,
            or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including
            without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i)
            your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third
            party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or
            alteration of your transmissions or content, whether based on warranty, contract, tort (including
            negligence) or any other legal theory, whether or not we have been informed of the possibility of such
            damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

        <h2>10. Governing Law</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of [Your State/Country], without
            regard to its conflict of law provisions.</p>

        <h2>11. Changes to Terms</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is
            material we will try to provide at least [e.g., 30] days' notice prior to any new terms taking effect. What
            constitutes a material change will be determined at our sole discretion.</p>
        <p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by
            the revised terms. If you do not agree to the new terms, please stop using the Service.</p>

        <h2>12. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us:</p>
        <p>By email: [Your Contact Email]</p>
        <!-- Add other contact methods if applicable -->
    </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
onMounted(() => {
    document.title = 'Terms of Service - DeepSocial AI';
});
</script>

<style scoped>
/* Use Tailwind's prose plugin for nice typography on content pages */
/* Or style manually */
.prose h1,
.prose h2 {
    color: var(--fallback-nc, oklch(var(--nc) / 1));
    /* DaisyUI neutral-content or similar */
}
</style>